#!/usr/bin/env bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# picom (if it exists)
if [ -x "$(command -v picom)" ]; then
  while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
  picom --config $SCRIPTPATH/picom/picom.conf &> /dev/null &
fi
##############################################################################

# [ WALLPAPERS ] #############################################################
sh $SCRIPTPATH/system_scripts/pkill_bc

# [ START STATUSBAR ] #########################################################
# Terminate already running bar instances
killall -q polybar
# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar -c=$SCRIPTPATH/polybar/config.ini menu &
echo "Polybar launched..."

#nm-applet #########################################################
nm-applet &

# power manager & polkit
xfce4-power-manager &

#lock #########################################################
xautolock -time 5 -locker $SCRIPTPATH/system_scripts/session_lock

#udisk #########################################################
udiskie -A

# notifications
if [ -x "$(command -v dunst)" ]; then
  pkill dunst
  dunst -config $SCRIPTPATH/dunst/dunstrc &
fi